ros-drivers/audio_common

sound_play/src/sound_play/libsoundplay.py
Should prevent warning being displayed whenever the client is created.
Fixes issue #43
=> sound_play: added queue_size to SoundClient init

sound_play/include/sound_play/sound_play.h, sound_play/msg/SoundRequest.msg, sound_play/scripts/play.py, sound_play/scripts/playbuiltin.py, sound_play/scripts/playpackage.py, sound_play/scripts/say.py, sound_play/scripts/soundplay_node.py, sound_play/scripts/test.py, sound_play/src/sound_play/libsoundplay.py, sound_play/test/test.cpp
Original request is #47. PR into this branch to add functionality to next version.
=> Add ability to specify volume level of sounds being played

sound_play/scripts/soundplay_node.py
Without the explicit queue_size the Publisher prints a warning message. This pull request removes this warning.
I separated a trailing whitespace removal commit.
=> Set queue_size in soundplay_node Publisher

sound_play/CMakeLists.txt
https://bugs.gentoo.org/show_bug.cgi?id=567466
=> sound_play: Fix build with -DCATKIN_ENABLE_TESTING=OFF.

audio_capture/launch/capture.launch, audio_capture/launch/capture_to_file.launch, audio_capture/launch/capture_wave.launch, audio_capture/src/audio_capture.cpp, audio_play/launch/play.launch
- Some of the gstreamer elements sometimes don't get created properly. I have added small snippets to check if these elements are properly created.
- Improvements to launch files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ros-drivers/audio_common/90)
=> Error checking code and improvements to launch files

audio_capture/src/audio_capture.cpp
The audio_capture proc was leaking.  I made it free things for each sample.
=> Fix audio_capture leak

audio_capture/package.xml, audio_common/package.xml, audio_common_msgs/package.xml, audio_play/package.xml, sound_play/package.xml
=> add maintainer

sound_play/scripts/play.py, sound_play/scripts/playbuiltin.py, sound_play/scripts/playpackage.py, sound_play/scripts/say.py, sound_play/scripts/shutup.py, sound_play/scripts/soundplay_node.py, sound_play/scripts/test.py, sound_play/scripts/test_actionlib_client.py
fix syntax for python3 for noetic
=> fix syntax for python3

audio_capture/src/audio_capture.cpp
fix filesink in audio_capture with wave format
=> [audio_capture] fix filesink for wave format

audio_capture/launch/capture.launch, audio_capture/launch/capture_to_file.launch, audio_capture/src/audio_capture.cpp
add `sample_format` in `audio_capture`
cc. @708yamaguchi
=> [audio_capture] add sample_format in audio_capture

audio_play/src/audio_play.cpp
The current branch cannot save files in `audio_play`.
I fix the problem and also support `wave` file saving function.
cc. @708yamaguchi
=> [audio_play] fix audio_play to save file

audio_capture/launch/capture.launch, audio_capture/launch/capture_to_file.launch
add bitrate arg in `capture.launch` and `capture_to_file.launch`
=> [audio_capture] add bitrate in capture launch

sound_play/scripts/playbuiltin.py, sound_play/scripts/playpackage.py, sound_play/scripts/say.py
=> Use rospy.myargv() instead of sys.argv to support remapping

sound_play/scripts/soundplay_node.py
set proper set_aborted in execute_cb
=> [sound_play] add proper set_aborted in soundplay_node.py

sound_play/scripts/soundplay_node.py
`start` `actionserver` after initialization in `soundplay_node.py`
=> [sound_play] start ActionServer after initialize in soundplay_node.py

sound_play/CMakeLists.txt, sound_play/scripts/is_speaking.py, sound_play/scripts/is_speeching.py, sound_play/soundplay_node.launch
Added is_speeching node to output the bool value of whether the robot is speaking.
=> Add is_speeching node for checking robot is speaking

sound_play/scripts/is_speaking.py
related to https://github.com/ros-drivers/audio_common/pull/176#issuecomment-1104946154
=> refactor is_speaking.py

sound_play/scripts/is_speaking.py
Related to #176 .
Changed speaking status to check the `status` of `GoalStatus`.
=> Improve is_speaking by checking goal status

sound_play/scripts/soundplay_node.py, sound_play/soundplay_node.launch
add `default_voice` arg in `soundplay_node.launch`
usage: (`festvox-us-slt-hts`)
```bash
roslaunch sound_play soundplay_node.launch default_voice:=voice_cmu_us_slt_arctic_hts
```
cc. @708yamaguchi @tkmtnt7000
=> add default_voice in soundplay_node.launch

sound_play/package.xml, sound_play/scripts/soundplay_node.py, sound_play/setup.py, sound_play/sound_play_plugin.yaml, sound_play/soundplay_node.launch, sound_play/src/sound_play/__init__.py, sound_play/src/sound_play/festival_plugin.py, sound_play/src/sound_play/sound_play_plugin.py, sound_play/src/sound_play/sound_type.py
add sound_play plugin feature for other texttospeech plugins
=> add soundplay plugin feature

sound_play/package.xml, sound_play/scripts/soundplay_node.py, sound_play/setup.py, sound_play/sound_play_plugin.yaml, sound_play/soundplay_node.launch, sound_play/src/sound_play/__init__.py, sound_play/src/sound_play/festival_plugin.py, sound_play/src/sound_play/flite_plugin.py, sound_play/src/sound_play/sound_play_plugin.py, sound_play/src/sound_play/sound_type.py
merge after #183 
with this PR, we can use `flite` in `sound_play`.
`flite` is lite version of `festival` and easy to add voice model.
https://github.com/festvox/flite
waiting for rosdistro: https://github.com/ros/rosdistro/pull/33225
=> add flite plugin for sound_play

sound_play/scripts/soundplay_node.py
=> fix typo in soundplay_node.py

sound_play/scripts/soundplay_node.py
add get_sound_length method and refactor soundplay_node.py
@708yamaguchi can you review this PR?
=> [sound_play] add get_sound_length method and refactor soundplay_node.py

sound_play/CMakeLists.txt
=> fix missing install in CMakeLists.txt

sound_play/scripts/soundplay_node.py
=> [sound_play] show error and skip loading when plugin yaml is missing

audio_common_msgs/CMakeLists.txt, audio_common_msgs/msg/AudioDataStamped.msg, audio_common_msgs/package.xml
related to #201 
I add `AudioDataStamped` msg, which has `Header`.
=> [audio_common_msgs] add AudioDataStamped.msg

audio_capture/launch/capture.launch, audio_capture/launch/capture_to_file.launch, audio_capture/launch/capture_wave.launch, audio_play/launch/play.launch
this PR update `audio_capture` and `audio_play` launch.
=> update audio_capture/audio_play launch

audio_capture/package.xml, audio_capture/src/audio_capture.cpp
This implementation works well for me and does not change behavior when combined with a simulator.
=> get capture audio stamp from gstreamer in real recording

audio_capture/src/audio_capture_node.cpp
Make sure that latecomers can get the codec details.
=> Publish audio_info on a schedule
