- sound_play/scripts/soundplay_node.py
There is already output going to `rospy.logdebug` in these locations, and having raw prints clutters the output.
> sound_play: remove some raw prints cluttering output

- audio_capture/CMakeLists.txt
- audio_capture/package.xml
- audio_capture/src/audio_capture.cpp
- audio_play/CMakeLists.txt
- audio_play/package.xml
- audio_play/src/audio_play.cpp
This fixes issue #50.
When the data stream on /audio stops the gstreamer pipeline is set to the 'pause' state. As soon as data arrives again the pipeline is set back to 'playing'.
As a first attempt to fix this issue I ported the audio_play and audio_capture packages to gstreamer 1.0 because 0.10 is deprecated but the issue remained.
This is the first time I put my hand on gstreamer so please correct me if I'm doing something wrong here.
Now against the master branch.
> Fix for audio_play to continue playing and port to gstreamer 1.0

- audio_play/src/audio_play.cpp
Before the sink buffer underflows the pipeline is paused. When data is received again the pipeline is set to playing again.
This fixes #50 without changing any dependencies.
> Fixed underflow.

- audio_capture/src/audio_capture.cpp
I applied the patch described in #18 (not sure why the code was never updated).
audio_capture should now be able to run for long periods of time without hogging up memory.
> Apply memory leak fix in audio_capture

- audio_capture/launch/capture_wave.launch
- audio_capture/src/audio_capture.cpp
- [audio_capture] add option to publish captured audio data as wav format
Currenly audio_capture node publishes only mp3 which need to be decode to use.
I added the option to publish captured audio data as wav format.
Also added sample launch file.
This PR is almost copied from https://github.com/ros-drivers/audio_common/pull/60 just to send another branch
> [audio_capture] add option to publish captured audio data as wav format

- sound_play/scripts/test_actionlib_client.py
This makes the script actually play the sounds it requests. The old behavior was confusing to me: I ran the script and heard nothing.
> Set the volume in each of the sound_play actionlib tests.

- sound_play/scripts/say.py
- sound_play/scripts/soundclient_example.py
- sound_play/src/sound_play/libsoundplay.py
The SoundClient can now be asked to wait until the requested sound has finished playing before returning, by making use of @aginika 's actionlib implementation. This removes the need for manual sleeping after a sound request is published. The default (out-of-the-box) behavior is unchanged (SoundClient returns immediately) so this should be transparent to everyone.
I also added an example (`soundclient_example.py`) that shows how to use the SoundClient in both blocking and non-blocking modes.
Lastly I snuck in some linting (trailing whitespace, new-style python classes), let me know if you object.
> Adds capability for blocking calls to SoundClient's play.

- sound_play/CMakeLists.txt
- sound_play/package.xml
- sound_play/scripts/test/test_sound_client.py
This PR demonstrates an instance of the missing dependency on actionlib ( #66 ).
It adds a unit test that just creates a SoundClient object. This test fails when running on a clean machine with all rosdep dependencies resolved, for example on Travis continuous integration [here](https://travis-ci.org/felixduvallet/audio_common/builds/92227443).
It also [fixes](https://travis-ci.org/felixduvallet/audio_common/builds/92228025) the problem by specifying the actionlib dependency in package.xml, so it should fix the issue.
> sound_client actionlib dependency fix

- sound_play/scripts/soundplay_node.py
This was resulting in the number of sink inputs reaching the maximum threshold,
(32 on ubuntu 14.04 with pulseaudio 4.0) after which no more sounds could be
played by the node. It would only happen if the rate of sounds being played was
slower than the dictionary cleanup.
Some files which can help illustrate the problem:
`sound_play/launch/sound_test.launch`
```
<launch>
<node pkg="sound_play" type="soundplay_node.py" name="soundplay_node"/>
<node pkg="sound_play" type="sound_test" name="sound_test"/>
</launch>
```
`sound_play/scripts/sound_test`
```
#!/usr/bin/env python
import os
import roslib
import rospy
from std_msgs.msg import Empty
from sound_play.libsoundplay import SoundClient
class SoundPlayer:
def sound_callback(self, msg):
self.sound_client.playWave(self.sound_file, 0.1)
def …
```
> [soundplay_node] fix resources not being released on dict cleanup

- sound_play/src/sound_play/libsoundplay.py
The tested conditions in sendMsg (in libsoundplay.py) are inverted, and the publisher is only checked for the blocking case, and the action client is only checked for the non-blocking case.
This leads to confusing error logs and situations.
> There's an error in testing for missign Publisher/action client in sendMsg

- audio_capture/launch/capture.launch
- audio_capture/src/audio_capture.cpp
- audio_play/launch/play.launch
Allows setting of input device from multiple without having to set that device to the default input, and multiple instances of audio_capture to run simultaneously on different sources.
> Provide alsasrc device as parameter

- audio_capture/src/audio_capture.cpp
0.10-style raw audio caps were being created, according to GStreamer warning. Should be audio/x-raw,format=(string).. now.
fixes #92
> fix(audio_capture): capturing wave using gst1.0

- audio_play/src/audio_play.cpp
We were seeing an issue when publishing mp3 clips.  The tail end of each clip was cut off and applied to the beginning of the next clip with varying intensity (but a short clip was almost always lost entirely).
It looked like the `need-data` event was causing a pipeline pause before the rest of the pipeline was drained.  Manually draining the pipeline seemed like a real chore, so I removed the pipeline pausing feature and set a property on the source allowing for the kind of ad hoc input we intend to feed it.
> audio_play: Fix mp3 clip overlap by never pausing the pipeline

- sound_play/scripts/soundplay_node.py
This basically checks from the actual volume level, which can be changed by OS UI and forces it to the volume passed by args.
This issue can be reproduced by sending command to play one sound multiple times and poking the volume from the volume settings bar.
> [sound_play] volume check for cached sounds

- sound_play/scripts/soundplay_node.py
Not specifying a sound device defaults to *the first* sound device starting from Ubuntu 16.04., not to the one configured as default.
The change is backward compatible and tested on ROS indigo and kinetic on a PR2 robot.
> use default audio output by default

- sound_play/scripts/soundplay_node.py
When robots try to speak japanese texts, they cannot encode the texts into `ISO-8859-15`.
For example, 
English OK:
```
In [1]: 'a'.decode('UTF-8').encode('ISO-8859-15')
Out[1]: 'a'
```
Japanese NG:
```
In [2]: 'あ'.decode('UTF-8').encode('ISO-8859-15')
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-2-aa06742ae966> in <module>()
----> 1 'あ'.decode('UTF-8').encode('ISO-8859-15')
/usr/lib/python2.7/encodings/iso8859_15.py in encode(self, input, errors)
10 
11     def encode(self,input,errors='strict'):
---> 12         return codecs.charmap_encode(input,errors,encoding_table)
13 
14     def decode(self,input,errors='strict'):
UnicodeEncodeError: 'charmap' codec can't encode …
```
> Do not encode text when using langages which ISO-8859-15 does not support

- sound_play/scripts/soundplay_node.py
`stop()` function in class `soundtype` seems not to free Gstreamer objects correctly.
Gstreamer object has to be unreferenced explicitly (cf. [Gst.Element.get_bus](https://lazka.github.io/pgi-docs/Gst-1.0/classes/Element.html#Gst.Element.get_bus)), otherwise causes a memory leak and leads the node to crash. #109
I tried to free the Gstreamer objects by substituting `None`.
> [sound_play/scripts/soundplay_node.py] fix Gstreamer memory leak

- README.md
- sound_play/CMakeLists.txt
- sound_play/package.xml
- sound_play/setup.py
- sound_play/src/sound_play/__init__.py
- sound_play/src/sound_play/libsoundplay.py
Note: test in sound_play is not working #134
> Noetic build

- sound_play/src/sound_play/libsoundplay.py
* Add two keywords to the constructor of SoundClient class in order to
specify actionlib namespace and topic name to play sound.
* See #119.
> Support use different topic and actionlib to play sound

- audio_play/launch/play.launch
- audio_play/src/audio_play.cpp
related to #104 
support wave format for audio_play.
I also use #122 for audio livestreaming by wave format as respeaker_node in https://github.com/jsk-ros-pkg/jsk_3rdparty
> [audio_play] support wave format 

- audio_capture/src/audio_capture.cpp
- audio_play/src/audio_play.cpp
support `sample_rate`, `sample_format`, `channels` for `mp3` in `audio_capture` and `audio_play`.
`sample_format` is introduced in #127 and #145 .
> [audio_play, audio_capture] support sample_rate, sample_format, channels for mp3

- audio_capture/src/audio_capture.cpp
The bitrate parameter of audio capture does not affect bitrate of published messages with mp3 encoding.
This is because lamemp3enc element in audio_capture use [quality property](https://gstreamer.freedesktop.org/documentation/lame/index.html#lamemp3enc:quality) instead of [bitrate property](https://gstreamer.freedesktop.org/documentation/lame/index.html#lamemp3enc:bitrate) if [target property](https://gstreamer.freedesktop.org/documentation/lame/index.html#lamemp3enc:target) is not changed.
I confirmed that this code works properly with the following script.
```
#!/usr/bin/env python
import rospy
from audio_common_msgs.msg import AudioData
import time
class MeasureAudioBitrate:
def __init__(self):
#
rospy.init_node( 'measure_audio_bitrate' )
#
topicname = 'audio'
#
self.subscriber = …
```
> Fix property of lamemp3enc element in audio_capture so that the bitrate parameter work properly.

- sound_play/scripts/soundplay_node.py
Currently if trying to use text-to-speech feature, the version released in noetic fails with the following error:
`$ rosrun sound_play say.py 'Hello Robot'`
```
(/sound_play) [ERROR] [1599147542.494601]: Exception in callback: 'str' object has no attribute 'decode', /tmp/test_audio_common_ws/src/audio_common/sound_play/scripts/soundplay_node.py:309
```
This PR catches the case a Python3 string is received and encodes it to file to be able to play it
> fix soundplay_node to handle Python3 strings

- audio_play/launch/play.launch
set `do_timestamp` as `false` for default behavior.
if everyone use this node with `false`, we can change the default behavior.
> [audio_play] set do_timestamp false

- sound_play/scripts/play.py
play.py uses `sys.argv` to parse the arguments.
The script does not support remapping like `robotsoud:=sound_play`.
Use `rospy.myargv()` in order to support remapping.
> Use rospy.myargv() instead of sys.argv to support remapping

- audio_capture/src/audio_capture.cpp
- audio_play/launch/play.launch
- audio_play/src/audio_play.cpp
This PR fixes `device` option warning reported in #159 .
Without this PR, `device` param is not correctly passed to gstreamer.
```
(audio_play:29143): GLib-GObject-WARNING **: 14:24:09.282: g_object_set_is_valid_property: object class 'GstAutoAudioSink' has no property named 'device'
```
- add `device` arg for `audio_play` `play.launch`
- add `depth` param in `audio_play` node
- use `alsasink`
- add `sync:false` for `alsasink`
> [audio_play] use alsasink and add device 

- audio_common_msgs/CMakeLists.txt
- audio_common_msgs/msg/AudioInfo.msg
From https://github.com/ros-drivers/audio_common/pull/148
I added `AudioInfo.msg` which includes audio meta data.
This information is not necessarily required for decoding audio data, but it may be helpful for the users to do some audio processing.
CC @knorth55 @sktometometo
> [audio_common_msgs] AudioInfo.msg to add audio meta data

- audio_capture/src/audio_capture.cpp
I add publisher to publish audio info once before publishing `/audio` topic.
I set `latch = true`, so later launched nodes can also subscribe to this audio info.
Here's a sample of the audio info:
```
$ roslaunch audio_capture capture.launch channels:=2 format:=mp3 sample_rate:=44100
$ rostopic echo /audio/audio_info                                                                          
channels: 2                                                                                          
sample_rate: 44100                                                                                   
sample_format: "S16LE"                                                                               
bitrate: 128 …
```
> [audio_capture] Publish audio info once before publishing /audio

- sound_play/src/sound_play/libsoundplay.py
I add `replace` argument in `sendMsg`.
when `replace` is `true`, `SoundClient` replace the audio commands. (default)
when `replace` is `false`, `SoundClient` waits until previous commands finish.
cc. @708yamaguchi
> [sound_play] add replace arg in sendMsg

- sound_play/scripts/soundplay_node.py
In current, a function for `SoundRequest.SAY ` cache voices. 
However, some users may include voice information in `arg2` value.
This PR adds `arg2` information for a cache key value.
> Add arg2 information for cache

- sound_play/scripts/soundplay_node.py
Handle playing sound in loop by:
* starting gobject thread to receive gstreamer messages
* seeking file beginning instead of stopping playback
* fixing a bug where all wave files where flagged as stale
* allowing multiple sound plays at the same time
> Handle playing sound in loop

- sound_play/scripts/soundplay_node.py
- sound_play/soundplay_node.launch
In current,  `sound_play`'s action server sleep `1.0 second`.
This sleep is a little long.
Some sounds take extra time to finish speaking.
This PR modifies the sleep time.
The sample code is as follows.
```
from datetime import datetime
import rospy
from sound_play.libsoundplay import SoundClient
rospy.init_node('say_node')
client = SoundClient(
sound_action='sound_play', sound_topic='sound_play',
blocking=True)
rospy.sleep(2.0)
while not rospy.is_shutdown():
start = datetime.now()
client.say('hello!')
end = datetime.now()
print(end - start)
```
```
roslaunch sound_play soundplay_node.launch loop_rate:=1
```
The result of the above code is as follows.
```
0:00:02.182967
0:00:02.020315
0:00:02.021195
0:00:02.020535
0:00:02.019667
0:00:02.019659
0:00:02.020918
```
```
roslaunch sound_play …
```
> Modified loop rate for action execution

- sound_play/src/sound_play/libsoundplay.py
Currently `sendMsg()` does not return when action server does not exist or no result is sent because timeout of `wait_for_server()` and `wait_for_result()` is set to zero. 
Some users want to escape the function even if action cannot be executed.
https://github.com/jsk-ros-pkg/jsk_robot/blob/34a129462403878c9b4c9c86c1aa9b38d506c143/jsk_fetch_robot/jsk_fetch_startup/scripts/battery_warning.py#L34 
https://github.com/jsk-ros-pkg/jsk_robot/pull/1589#discussion_r967561657
> Add timeout to wait_for_server and wait_for_result

- audio_play/src/audio_play.cpp
Solve issues reported in #205 .
I add `gst_buffer_unref` when the `GstBuffer` is no more used.
I add the line in `audio_play` and `audio_capture`.
> Avoid memory leak in audio_play

- audio_capture/src/audio_capture.cpp
- audio_play/src/audio_play.cpp
Private namespacing is redundant in ros2. This will allow the launch args to actually edit the values - the in-code defaults were being used thus far.
> Removing ros1 namespacing

- sound_play/package.xml
this PR adds missing `rosidl_generator_py` in `buildtool_depend`.
> add rosidl_generator_py in buildtool_depend

- audio_capture/src/audio_capture.cpp
this PR change to publish both `AudioData` and `AudioDataStamped` topic from `audio_capture.cpp`.
> publish audio_stamped in audio_capture.cpp

- sound_play/src/sound_play/flite_plugin.py
Fixes https://github.com/ros-drivers/audio_common/issues/228
This PR is for reducing the time to import the python module by deferring the usage of the `rospkg.Rospack.get_path` to when it is needed for the first time.
It also fixes invalid code which refers to a member variable which does not exist. (`self._default_voice`)
> FlitePlugin: Lazy loading default voice path

- audio_play/launch/record_to_file.launch
Related to https://github.com/jsk-ros-pkg/jsk_common/pull/1791
There is [a function to save audio topics to a file](https://github.com/ros-drivers/audio_common/blob/836aa62522764ee7b8e4925b87ec7d84cfdd552c/audio_play/src/audio_play.cpp#L74-L79 ) in `audio_play` , but it is currently difficult to find, so I wrote a record_to_file.launch file following the example of `audio_capture`'s `capture_to_file.launch`.
> [audio_play] Add record_to_file.launch

- audio_capture/src/audio_capture_node.cpp
Allows use of pulsesrc and other options.
> Allow audio_capture node to specify src type
